version: "3.6"

volumes:
  prometheus_data: {}

services:
  api:
    image: cesi
    ports:
      - 3000:3000
    networks:
      - prometheus
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - prometheus
  grafana:
    image: grafana/grafana
    ports:
      - 3001:3000
    networks:
      - prometheus

networks:
  prometheus:
    driver: bridge